// Parses every PDF in exams/ into data/questions.json and writes docs/parse-report.md.
// Usage: npm run parse
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { readPdfPages } from './lib/pdf-lines.ts';
import { parsePages } from './lib/parser.ts';
import {
  buildExamQuestions,
  dedupe,
  detectMeta,
  examInfo,
  fillPiDescriptions,
  type ExamMeta,
  type MetaOverride,
} from './lib/build.ts';
import type { Question, QuestionBank } from '../src/lib/types.ts';

const root = path.resolve(import.meta.dirname, '..');
const examsDir = path.join(root, 'exams');
const areas: Record<string, string> = JSON.parse(
  fs.readFileSync(path.join(root, 'scripts', 'pi-areas.json'), 'utf8'),
).areas;
const manifestPath = path.join(examsDir, 'manifest.json');
const overrides: Record<string, MetaOverride> = fs.existsSync(manifestPath)
  ? JSON.parse(fs.readFileSync(manifestPath, 'utf8'))
  : {};

interface ExamReport {
  meta: ExamMeta;
  pages: number;
  questionsFound: number;
  keysFound: number;
  problems: string[];
  review: Question[];
  rationaleMismatches: number;
  piWithDescription: number;
}

const files = fs
  .readdirSync(examsDir)
  .filter((f) => f.toLowerCase().endsWith('.pdf'))
  .sort();
const seenHashes = new Map<string, string>();
const skipped: { file: string; reason: string }[] = [];
const perExam: { meta: ExamMeta; questions: Question[] }[] = [];
const reports: ExamReport[] = [];
const usedIds = new Set<string>();

for (const file of files) {
  const buf = fs.readFileSync(path.join(examsDir, file));
  const hash = crypto.createHash('sha256').update(buf).digest('hex');
  const dupOf = seenHashes.get(hash);
  if (dupOf) {
    skipped.push({ file, reason: `byte-identical to ${dupOf}` });
    continue;
  }
  seenHashes.set(hash, file);
  const pages = await readPdfPages(path.join(examsDir, file));
  const chars = pages.reduce((n, p) => n + p.lines.reduce((m, l) => m + l.segments.length, 0), 0);
  if (chars < 50) {
    skipped.push({ file, reason: 'no text layer (image-only PDF); OCR it first, see README' });
    continue;
  }
  const meta = detectMeta(pages, file, overrides[file]);
  let id = meta.id;
  for (let i = 2; usedIds.has(id); i++) id = `${meta.id}-${i}`;
  meta.id = id;
  usedIds.add(id);
  const parsed = parsePages(pages);
  const built = buildExamQuestions(parsed, meta, areas);
  perExam.push({ meta, questions: built.questions });
  reports.push({
    meta,
    pages: pages.length,
    questionsFound: parsed.questions.length,
    keysFound: parsed.keys.length,
    problems: built.problems,
    review: built.questions.filter((q) => q.needsReview),
    rationaleMismatches: built.rationaleMismatches,
    piWithDescription: built.questions.filter((q) => q.piDescription).length,
  });
}

perExam.sort((a, b) => a.meta.year - b.meta.year || a.meta.id.localeCompare(b.meta.id));
reports.sort((a, b) => a.meta.year - b.meta.year || a.meta.id.localeCompare(b.meta.id));

const { questions, examOrder, duplicates, conflicts } = dedupe(perExam);
const filled = fillPiDescriptions(questions);

const exams = perExam.map(({ meta }) => examInfo(meta, examOrder.get(meta.id)!));
// Mark whole-exam duplicates (e.g. the same Test number published twice).
for (const e of exams) {
  const owners = new Map<string, number>();
  for (const qid of e.questionIds) {
    const q = qid && questions.find((x) => x.id === qid);
    if (q && q.exam !== e.id) owners.set(q.exam, (owners.get(q.exam) ?? 0) + 1);
  }
  const [top] = [...owners.entries()].sort((a, b) => b[1] - a[1]);
  if (top && top[1] >= 90) e.duplicateOf = top[0];
}

const instructionalAreas = [...new Set(questions.map((q) => q.instructionalArea))].sort();
const bank: QuestionBank = {
  generatedAt: new Date().toISOString(),
  exams,
  questions,
  instructionalAreas,
};
fs.mkdirSync(path.join(root, 'data'), { recursive: true });
fs.writeFileSync(path.join(root, 'data', 'questions.json'), JSON.stringify(bank, null, 1) + '\n');

// ---------------------------------------------------------------- report
const usable = questions.filter((q) => !q.needsReview);
let md = `# Parse report\n\nGenerated by \`npm run parse\`. Source: \`exams/*.pdf\`. Output: \`data/questions.json\`.\n\n`;
md += `## Summary\n\n`;
md += `- PDF files: ${files.length} (${skipped.length} skipped)\n`;
md += `- Exams parsed: ${reports.length}\n`;
md += `- Question slots parsed: ${reports.reduce((n, r) => n + r.questionsFound, 0)}\n`;
md += `- Duplicate questions merged: ${duplicates.length}\n`;
md += `- Unique questions: ${questions.length}\n`;
md += `- Usable (not flagged): ${usable.length}\n`;
md += `- Flagged needsReview (hidden in the app by default): ${questions.length - usable.length}\n`;
md += `- PI descriptions filled in from another exam with the same PI code: ${filled}\n`;
md += `- Questions still without a PI description: ${questions.filter((q) => !q.piDescription).length} (their PI code was only ever printed without a description)\n\n`;
const restated = questions.filter((q) => !q.reviewNotes.some((n) => /rationale/.test(n))).length;
md += `### Validation checks\n\n`;
md += `Every exam must have 100 questions and 100 key entries. Every question must have a non-empty stem, 4 non-empty options (in A-D order, or A,C,B,D for two-column layouts), a correct letter, a rationale, and a PI code whose prefix is in \`scripts/pi-areas.json\`. Options must not contain boilerplate or a second option marker.\n\n`;
md += `Cross-check: MBA Research rationales start by restating the correct option. **${restated} of ${questions.length}** unique questions pass this check (the rationale starts with the keyed option's text). A rationale that restates a *different* option would flag the question as needsReview; none do.\n\n`;
if (skipped.length) {
  md += `### Skipped files\n\n| File | Reason |\n|---|---|\n`;
  for (const s of skipped) md += `| ${s.file} | ${s.reason} |\n`;
  md += '\n';
}
md += `## Per exam\n\n| Exam | File | Pages | Questions | Key entries | Flagged | PI desc. printed | Duplicate of |\n|---|---|---|---|---|---|---|---|\n`;
for (const r of reports) {
  const e = exams.find((x) => x.id === r.meta.id)!;
  md += `| ${r.meta.label} (\`${r.meta.id}\`) | ${r.meta.file} | ${r.pages} | ${r.questionsFound} | ${r.keysFound} | ${r.review.length} | ${r.piWithDescription} | ${e.duplicateOf ?? ''} |\n`;
}
md += `\n## Instructional areas (unique usable questions)\n\n| Area | Questions |\n|---|---|\n`;
for (const a of instructionalAreas) md += `| ${a} | ${usable.filter((q) => q.instructionalArea === a).length} |\n`;
md += `\n## Problems\n\n`;
let any = false;
for (const r of reports) {
  const minor = questions.filter((q) => q.exam === r.meta.id && !q.needsReview && q.reviewNotes.length);
  if (!r.problems.length && !r.review.length && !minor.length) continue;
  any = true;
  md += `### ${r.meta.label} (\`${r.meta.id}\`)\n\n`;
  for (const p of r.problems) md += `- **Exam:** ${p}\n`;
  for (const q of r.review) md += `- **Q${q.number} flagged:** ${q.reviewNotes.join('; ')}\n`;
  for (const q of minor) md += `- Q${q.number} note (not flagged): ${q.reviewNotes.join('; ')}\n`;
  md += '\n';
}
if (conflicts.length) {
  any = true;
  md += `### Duplicate conflicts\n\n`;
  for (const c of conflicts) md += `- ${c}\n`;
  md += '\n';
}
if (!any) md += `No problems found.\n`;
fs.writeFileSync(path.join(root, 'docs', 'parse-report.md'), md);

console.log(
  `Parsed ${reports.length} exams: ${questions.length} unique questions, ${usable.length} usable, ${questions.length - usable.length} flagged, ${duplicates.length} duplicates merged.`,
);
for (const r of reports)
  console.log(`  ${r.meta.id.padEnd(22)} q=${r.questionsFound} k=${r.keysFound} flagged=${r.review.length} ${r.problems.join('; ')}`);
