// Loads the parsed question bank (data/questions.json, generated by `npm run parse`).
// Imported as a raw string so TypeScript does not have to infer a type for a 2 MB literal.
import raw from '../../data/questions.json?raw';
import type { ExamInfo, Question, QuestionBank } from '../lib/types';

export const bank: QuestionBank = JSON.parse(raw);

export const allQuestions: Question[] = bank.questions;
export const byId = new Map<string, Question>(allQuestions.map((q) => [q.id, q]));
export const exams: ExamInfo[] = bank.exams;
export const examById = new Map<string, ExamInfo>(exams.map((e) => [e.id, e]));
export const areas: string[] = bank.instructionalAreas;

/** Questions shown in the app: flagged (needsReview) ones are hidden unless the setting is on. */
export function visibleQuestions(includeFlagged: boolean): Question[] {
  return includeFlagged ? allQuestions : allQuestions.filter((q) => !q.needsReview);
}

export function examLabel(id: string): string {
  return examById.get(id)?.label ?? id;
}
